-- ============================================================
-- Y/B — seed data (matches src/data/*.ts)
-- Run after schema.sql. Idempotent: re-running updates in place.
-- ============================================================

insert into public.services (slug, title, description, icon, sort_order) values
  ('web', 'Web Development',
   'Modern websites & web apps. Fast, accessible, built to scale — from landing pages to full products.',
   'M8 6l-5 6 5 6M16 6l5 6-5 6M13 4l-2 16', 1),
  ('security', 'Cybersecurity',
   'Secure-by-design builds, audits and hardening. We attack our own work before anyone else can.',
   'M12 2l8 4v6c0 5-3.5 8.5-8 10-4.5-1.5-8-5-8-10V6l8-4z M9 12l2 2 4-4', 2),
  ('systems', 'Custom Systems',
   'Dashboards, internal tools and automation that remove busywork and surface the numbers that matter.',
   'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M17.5 14v7 M14 17.5h7', 3),
  ('design', 'UI/UX & Branding',
   'Identity and interfaces that convert. Design is not decoration — it''s how the product argues for itself.',
   'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z M12 3a9 9 0 0 1 0 18 M7 12h10', 4)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  icon = excluded.icon,
  sort_order = excluded.sort_order;

insert into public.projects
  (slug, title, year, category, tags, summary, problem, solution, stack, results, sort_order)
values
  ('atlas-commerce', 'Atlas Commerce', '2026', 'web',
   array['Next.js','Stripe','Headless'],
   'A headless storefront for a Moroccan artisan collective selling into the EU market.',
   'The collective ran on a slow legacy theme: 9-second mobile loads, a 70% cart abandonment rate, and no way to localize pricing or content for European buyers.',
   'Rebuilt as a headless Next.js storefront with edge-rendered product pages, Stripe for multi-currency checkout, and a translation-ready CMS so the team publishes in three languages without touching code.',
   array['Next.js','TypeScript','Stripe','Sanity','Vercel'],
   array['Largest Contentful Paint cut from 9.1s to 1.2s on mid-range mobiles',
         'Checkout conversion up 38% in the first quarter',
         'Content team publishes independently — zero developer tickets for copy changes'],
   1),
  ('finguard-audit', 'FinGuard Audit', '2026', 'security',
   array['Pentest','OWASP','Hardening'],
   'Full application security audit and hardening pass for a fintech onboarding platform.',
   'Ahead of a banking partnership, the platform needed a third-party security review. Internal tests had never covered authorization logic or the mobile API surface.',
   'Ran a structured OWASP-based assessment across web and API: authorization matrix testing, session lifecycle review, and infrastructure hardening. Delivered fixes with the findings, not just a PDF of problems.',
   array['Burp Suite','OWASP ASVS','Node.js','PostgreSQL','Docker'],
   array['14 findings including 2 critical IDORs in the KYC document flow — all fixed and retested',
         'Session and token policy rewritten; account takeover paths closed',
         'Passed the partner bank''s independent review on the first attempt'],
   2),
  ('medina-logistics-os', 'Medina Logistics OS', '2025', 'systems',
   array['Dashboard','Realtime','Postgres'],
   'A realtime operations dashboard replacing WhatsApp threads and spreadsheets for a delivery fleet.',
   'Dispatch for 40+ drivers ran on group chats and a shared spreadsheet. No live view of deliveries, no accountability trail, and end-of-day reconciliation took two hours.',
   'Built an internal OS: live delivery map, driver assignment queue, and automatic reconciliation — backed by Postgres with realtime subscriptions so dispatch sees status changes the second they happen.',
   array['React','Supabase','PostgreSQL','Mapbox','Tailwind'],
   array['Daily reconciliation reduced from ~2 hours to under 5 minutes',
         'Failed-delivery rate down 22% with live exception alerts',
         'Onboarded the full fleet in one week — no training manual needed'],
   3),
  ('studio-noir', 'Studio Noir Portfolio', '2025', 'web',
   array['Design','Motion','3D'],
   'An award-bait portfolio site for a photography duo, built around motion and negative space.',
   'The duo''s work was strong but their site was a default template grid — indistinguishable from ten thousand others and invisible to the agencies they wanted to attract.',
   'Designed and built a custom experience: WebGL image distortion on scroll, a film-strip navigation metaphor, and an editorial type system. Every interaction tuned to keep the photography as the loudest element on the page.',
   array['Next.js','Framer Motion','WebGL','Vercel'],
   array['Featured on two design showcase galleries within a month of launch',
         'Average session time tripled compared to the old template',
         'Three agency inquiries directly attributed to the site in the first quarter'],
   4),
  ('vaultpass-recon', 'VaultPass Recon', '2025', 'security',
   array['Bug Bounty','API Security'],
   'Authorized security research engagement against a password manager''s public API surface.',
   'The vendor''s bug bounty program had gone quiet — the easy findings were gone, and they wanted depth: business-logic and API authorization flaws automated scanners can''t reach.',
   'Systematic recon and API mapping, then focused manual testing of sharing, recovery and team-vault flows — the places where authorization logic gets complicated and assumptions break.',
   array['Burp Suite','Python','OWASP','GraphQL'],
   array['Critical vault-sharing authorization flaw reported and patched within 72 hours',
         'Two high-severity findings in the account recovery flow',
         'Engagement extended — now a standing quarterly review'],
   5),
  ('sahara-booking', 'Sahara Booking Engine', '2024', 'systems',
   array['Automation','API','CRM'],
   'A booking and CRM automation engine for a desert tour operator drowning in manual admin.',
   'Every booking arrived by email or Instagram DM and was re-typed into three different systems. Double-bookings were monthly events and deposits regularly went untracked.',
   'Built a central booking engine with availability rules, automated deposit links, and a lightweight CRM. Inbound requests from every channel land in one queue with one source of truth for the calendar.',
   array['Node.js','PostgreSQL','Stripe','Twilio','React'],
   array['Double-bookings eliminated — zero incidents in the first season',
         'Admin time per booking cut from ~25 minutes to under 3',
         'Deposit collection rate up to 98% with automated payment links'],
   6)
on conflict (slug) do update set
  title = excluded.title,
  year = excluded.year,
  category = excluded.category,
  tags = excluded.tags,
  summary = excluded.summary,
  problem = excluded.problem,
  solution = excluded.solution,
  stack = excluded.stack,
  results = excluded.results,
  sort_order = excluded.sort_order;
